import fontforge, json

__all__ = [
    "FONTFORGE_FONT_ATTR_NAMES",
    "FONTFORGE_GLYPH_ATTR_NAMES",
]

FONTFORGE_FONT_ATTR_NAMES = [
    "activeLayer",
    "ascent",
    "bitmapSizes",
    "capHeight",
    "changed",
    "cidcopyright",
    "cidfamilyname",
    "cidfontname",
    "cidfullname",
    "cidordering",
    "cidregistry",
    "cidsubfont",
    "cidsubfontcnt",
    "cidsubfontnames",
    "cidsupplement",
    "cidversion",
    "cidweight",
    "comment",
    "copyright",
    "cvt",
    "default_base_filename",
    "descent",
    "design_size",
    "em",
    "encoding",
    "familyname",
    "fondname",
    "fontlog",
    "fontname",
    "fullname",
    "gasp",
    "gasp_version",
    "gpos_lookups",
    "gsub_lookups",
    "guide",
    "hasvmetrics",
    "head_optimized_for_cleartype",
    "hhea_ascent",
    "hhea_ascent_add",
    "hhea_descent",
    "hhea_descent_add",
    "hhea_linegap",
    "horizontalBaseline",
    "is_cid",
    "is_quadratic",
    "isnew",
    "italicangle",
    "macstyle",
    "layer_cnt",
    "layers",
    "loadState",
    "maxp_FDEFs",
    "maxp_IDEFs",
    "maxp_maxStackDepth",
    "maxp_storageCnt",
    "maxp_twilightPtCnt",
    "maxp_zones",
    "multilayer",
    "onlybitmaps",
    "os2_capheight",
    "os2_codepages",
    "os2_family_class",
    "os2_fstype",
    "os2_panose",
    "os2_strikeypos",
    "os2_strikeysize",
    "os2_stylemap",
    "os2_subxoff",
    "os2_subxsize",
    "os2_subyoff",
    "os2_subysize",
    "os2_supxoff",
    "os2_supxsize",
    "os2_supyoff",
    "os2_supysize",
    "os2_typoascent",
    "os2_typoascent_add",
    "os2_typodescent",
    "os2_typodescent_add",
    "os2_typolinegap",
    "os2_unicoderanges",
    "os2_use_typo_metrics",
    "os2_vendor",
    "os2_version",
    "os2_weight",
    "os2_weight_width_slope_only",
    "os2_width",
    "os2_winascent",
    "os2_winascent_add",
    "os2_windescent",
    "os2_windescent_add",
    "os2_xheight",
    "path",
    "persistent",
    "math",
    "private",
    "privateState",
    "selection",
    "sfd_path",
    "sfnt_names",
    "sfntRevision",
    "size_feature",
    "strokedfont",
    "strokewidth",
    "style_set_names",
    "temporary",
    "texparameters",
    "uniqueid",
    "upos",
    "userdata",
    "uwidth",
    "version",
    "verticalBaseline",
    "vertical_origin",
    "vhea_linegap",
    "weight",
    "woffMajor",
    "woffMinor",
    "woffMetadata",
    "xHeight",
]

FONTFORGE_GLYPH_ATTR_NAMES = [
    "activeLayer",
    "altuni",
    "anchorPoints",
    "anchorPointsWithSel",
    "background",
    "changed",
    "color",
    "comment",
    "dhints",
    "encoding",
    "font",
    "foreground",
    "glyphclass",
    "glyphname",
    "hhints",
    "horizontalComponents",
    "horizontalComponentItalicCorrection",
    "horizontalVariants",
    "isExtendedShape",
    "italicCorrection",
    "layer_cnt",
    "layers",
    "layerrefs",
    "lcarets",
    "left_side_bearing",
    "manualHints",
    "mathKern.bottomLeft",
    "mathKern.bottomRight",
    "mathKern.topLeft",
    "mathKern.topRight",
    "originalgid",
    "persistent",
    "references",
    "right_side_bearing",
    "script",
    "temporary",
    "texheight",
    "texdepth",
    "topaccent",
    "ttinstrs",
    "unicode",
    "unlinkRmOvrlpSave",
    "user_decomp",
    "userdata",
    "vhints",
    "validation_state",
    "verticalComponents",
    "verticalComponentItalicCorrection",
    "verticalVariants",
    "width",
    "vwidth",
]

def get_valid_font_attr_names(exclude_json=False):
    font = fontforge.font()
    attr_names = get_valid_attr_names(font,
                                      FONTFORGE_FONT_ATTR_NAMES,
                                      exclude_json=exclude_json)
    font.close()
    return sorted(attr_names)

def get_valid_glyph_attr_names(exclude_json=False):
    font = fontforge.font()
    glyph = font.createChar(32)
    attr_names = get_valid_attr_names(glyph,
                                      FONTFORGE_GLYPH_ATTR_NAMES,
                                      exclude_json=exclude_json)
    font.close()
    return sorted(attr_names)

def get_valid_attr_names(obj, attr_names, exclude_json=False):
    valid_attr_names = []
    for attr_name in attr_names:
        try:
            value = getattr(obj, attr_name)
        except:
            continue
        if exclude_json:
            try:
                json_txt = json.dumps(value)
            except:
                continue
        valid_attr_names.append(attr_name)
    return valid_attr_names
