__all__ = [
    "UNICODE"
]

UNICODE = {
    "LATIN_SMALL_LETTER_SCHWA": 0x0259,
    "GREEK_SMALL_LETTER_BETA": 0x03B2,
    "GREEK_SMALL_LETTER_GAMMA": 0x03B3,
    "GREEK_SMALL_LETTER_RHO": 0x03C1,
    "GREEK_SMALL_LETTER_PHI": 0x03C6,
    "GREEK_SMALL_LETTER_CHI": 0x03C7,
}
